# Generated by Django 5.2.4 on 2025-10-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='xp',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
