# Generated by Django 5.2.4 on 2025-10-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resource_xp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('skill', 'order')},
        ),
    ]
