# Generated by Django 5.2.4 on 2025-10-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='skill',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
