# Generated by Django 5.2.4 on 2025-10-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='skills', to='core.tag'),
        ),
    ]
