# Generated by Django 5.2.4 on 2025-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='module_title',
            field=models.CharField(blank=True, help_text="e.g., 'Module 1: Python Basics'", max_length=100, null=True),
        ),
    ]
